services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "${AMQP_PORT:-5672}:5672"
      - "${UI_PORT:-15672}:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
  order-db:
    image: postgres:18
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_ORDER_DB}
    volumes:
      - order_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "psql -U postgres -d ${POSTGRES_ORDER_DB} -c 'SELECT 1' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
  inventory-db:
    image: postgres:18
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_INVENTORY_DB}
    volumes:
      - inventory_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "psql -U postgres -d ${POSTGRES_INVENTORY_DB} -c 'SELECT 1' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
  payment-db:
    image: postgres:18
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_PAYMENT_DB}
    volumes:
      - payment_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "psql -U postgres -d ${POSTGRES_PAYMENT_DB} -c 'SELECT 1' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
  order-service:
    build: ./order-service
    ports:
      - "${ORDER_API_PORT:-8010}:8010"
    environment:
      - AMQP_URL=${AMQP_URL}
      - POSTGRES_DB=${POSTGRES_ORDER_DB}
    volumes:
      - ./order-service:/app
    healthcheck:
      test: ["CMD-SHELL", "curl -X 'GET' 'http://localhost:8010/api/v1/health' -H 'accept: application/json'"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      rabbitmq:
        condition: service_healthy
      order-db:
        condition: service_healthy
    env_file:
      - .env
  inventory-service:
    build: ./inventory-service
    ports:
      - "${INVENTORY_API_PORT:-8011}:8010"
    environment:
      - AMQP_URL=${AMQP_URL}
      - POSTGRES_DB=${POSTGRES_INVENTORY_DB}
    volumes:
      - ./inventory-service:/app
    healthcheck:
      test: ["CMD-SHELL", "curl -X 'GET' 'http://localhost:8010/api/v1/health' -H 'accept: application/json'"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      - rabbitmq
      - inventory-db
    env_file:
      - .env
  payment-service:
    build: ./payment-service
    ports:
      - "${PAYMENT_API_PORT:-8012}:8010"
    environment:
      - AMQP_URL=${AMQP_URL}
      - POSTGRES_DB=${POSTGRES_PAYMENT_DB}
    volumes:
      - ./payment-service:/app
    healthcheck:
      test: ["CMD-SHELL", "curl -X 'GET' 'http://localhost:8010/api/v1/health' -H 'accept: application/json'"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      - rabbitmq
      - payment-db
    env_file:
      - .env
  notification-service:
    build: ./notification-service
    ports:
      - "${NOTIFICATION_API_PORT:-8013}:8010"
    environment:
      - AMQP_URL=${AMQP_URL}
    volumes:
      - ./notification-service:/app
    healthcheck:
      test: ["CMD-SHELL", "curl -X 'GET' 'http://localhost:8010/api/v1/health' -H 'accept: application/json'"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      - rabbitmq
    env_file:
      - .env

volumes:
  rabbitmq_data:
  order_data:
  inventory_data:
  payment_data:
  order-service:
